# =============================================================
# agents/compiler.py — The Compiler Agent (Phase 2 — updated)
# =============================================================
# WHAT CHANGED FROM PHASE 1:
#   ★ Reads state["memory_context"] — past session summaries
#   ★ Reads state["rag_context"]    — historical comparison data
#   ★ New report section: "📅 Historical Trends" that uses
#     rag_context to show how metrics have changed over time
#   ★ Compiler is now instructed to explicitly use historical
#     data when it exists (this was the synthesis gap in Phase 1)
# =============================================================

from langchain_core.messages import HumanMessage, SystemMessage

from state import MarketingState
from utils.llm import get_llm


COMPILER_SYSTEM_PROMPT = """You are a senior marketing analyst writing a professional intelligence report.

You receive:
- The marketer's original question
- A plan showing what sub-tasks were analyzed
- Internal data findings (CSV analysis)
- External research findings (web research)
- Memory context from past sessions (★ Phase 2)
- RAG historical data for trend comparison (★ Phase 2)

REQUIRED output format (always use EXACTLY these headers):

# 📊 Marketing Intelligence Report

## 🎯 Original Request
[One clear sentence restating what the marketer asked]

## 🗺️ Analysis Performed
[Bullet list of completed sub-tasks]

## 📈 Internal Data Findings
[Specific numbers, channel names, percentages from data analysis.
**Bold** the most important metric. If none: "Not applicable."]

## 🌐 External Research Insights
[Key trends, benchmarks, best practices from web research.
If none: "Not applicable."]

## 📅 Historical Trends & Comparisons
[★ NEW Phase 2 section]
[Use the RAG historical data to show how metrics changed over time.
Example: "In the previous analysis (Jan 15), email revenue was $28K. 
Current session shows $31K — a 10.7% increase."
If no historical data: "No previous sessions to compare. This is the baseline."]

## 🔗 Key Connections
[2-3 specific connections between internal data and external research.
Also connect to historical trends where relevant.
Example: "Our engagement rate of 88% exceeds the industry benchmark of 8-12%,
and has improved from 82% in the previous session."]

## ✅ Actionable Recommendations
[3-5 specific recommendations grounded in data, research, and history.
Start each with a verb: Increase, Reduce, Test, Shift, Reallocate, Pause.]

---
*Report generated by Multi-Agent BI Assistant (Phase 2) | Sources: Internal Data + Web Research + Memory*

STRICT RULES:
- Never hallucinate numbers. Only use values that appear in the provided context.
- If a section has no data: write "Not applicable for this query."
- Be direct and specific. No vague statements.
- Use **bold** for key metrics and ⚠️ for warnings."""


def compiler_agent(state: MarketingState) -> dict:
    """
    Compiler Agent Node (Phase 2).

    Reads:  state["query"], state["plan"], state["coding_output"],
            state["research_output"], state["memory_context"], state["rag_context"] ★
    Writes: state["final_report"]
    """
    print("\n📝 [COMPILER] Synthesizing all findings into final report...")

    llm = get_llm(temperature=0.1)

    plan_text = "\n".join(
        f"  - [{('✅' if t['source'] in ('INTERNAL', 'BOTH') else '🌐')}] {t['task']}"
        for t in state.get("plan", [])
    )

    coding_out  = state.get("coding_output",  "No internal data analysis was performed.")
    research_out = state.get("research_output", "No external research was performed.")

    # ★ Phase 2: include memory and RAG context
    memory_ctx = state.get("memory_context", "")
    rag_ctx    = state.get("rag_context", "No historical data available for comparison.")

    source_note = ""
    if "No internal data analysis required" in coding_out:
        source_note = "NOTE: Only external research was performed."
    elif "No external research required" in research_out:
        source_note = "NOTE: Only internal data analysis was performed."

    user_message = (
        f"Original Marketer Query: {state['query']}\n\n"
        f"Sub-tasks Executed:\n{plan_text}\n\n"
        f"{source_note}\n\n"

        f"--- INTERNAL DATA FINDINGS ---\n{coding_out}\n\n"
        f"--- EXTERNAL RESEARCH FINDINGS ---\n{research_out}\n\n"

        # ★ Phase 2 additions
        f"--- MEMORY CONTEXT (Past Similar Sessions) ---\n"
        f"{memory_ctx if memory_ctx else 'No relevant past sessions found.'}\n\n"
        f"--- RAG HISTORICAL DATA (For Trend Comparison) ---\n{rag_ctx}\n\n"

        f"Write the complete Marketing Intelligence Report. "
        f"Use the Historical Trends section to highlight any changes vs past sessions."
    )

    response = llm.invoke([
        SystemMessage(content=COMPILER_SYSTEM_PROMPT),
        HumanMessage(content=user_message),
    ])

    print("   ✅ Report compiled successfully.")
    return {"final_report": response.content}